version: '1.0'
services:
  backend:
    image: imageback
    container_name: back
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: imagefront
    container_name: front
    ports:
      - "8085:80"
    depends_on:
      - backend
      - db

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: iesports
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
